name: 'Build and Publish Docker Image'

on:
  push:
    branches:
      - 'feat/*'

jobs:
  build-and-push:
    # needs: [publish-to-npm]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./docker/images/n8n
        build-args: |
            N8N_VERSION=${{ needs.publish-to-npm.outputs.release }}
        platforms: linux/amd64,linux/arm64
        provenance: false
        push: true
        tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/n8n:${{ needs.publish-to-npm.outputs.release }}
            ghcr.io/${{ github.repository_owner }}/n8n:${{ needs.publish-to-npm.outputs.release }}

